[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
